# This file is part of the testing setup for the internet_structure package
# It is generated by usethis::use_testthat()
#
# To run tests interactively:
#   devtools::test()
#
# To run tests in batch mode:
#   devtools::test_file("tests/testthat/test-data-collection.R")

library(testthat)
library(internet_structure)

test_check("internet_structure")
